config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :topics do
    resources :posts
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get 'contact' => 'welcome#contact'
  get 'about' => 'welcome#about'
  get 'faq' => 'welcome#faq'

  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :topics, only: [:index, :show]
    end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  default_scope { order('updated_at DESC') }


  # Scope is a method that generates methods
  # Its first argument is the name of the method to generate
  # Its second argument provides the logic to run:
        # We use the lambda syntax (-> with a block { ... }) to implement
        # the method's logic
  # the visible_to scope will run the code inside the lambda on the relation
  # or class on which it's called
  # To make it work properly we require an if statement in TopicsController to
  # determine if a user is signed in.
  # lambda block's syntax:
      # This syntax is called the ternary operator:
      # if_this_is_a_true_value ? then_the_result_is_this : else_it_is_this
      # It's like an if statement like:
          # if A then B else C end is the same as a ? b : c
  scope :visible_to, -> (user) { user ? all : where(public: true) }
  # It now returns the equivalent of Topic.all or Topic.where(public: true)
  # depending on the value of user (present or nil)


end

app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < Api::V1::BaseController

  before_action :authenticate_user, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]

  def index
    topics = Topic.all
    render json: topics, status: 200
  end

  def show
    topic = Topic.find(params[:id])
    render json: topic, status: 200
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :require_sign_in, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]

  def index
    @topics = Topic.visible_to(current_user)
  end

  def show
    @topics = Topic.visible_to(current_user)
    @topic = Topic.find(params[:id])

    unless @topic.public || current_user
      flash[:alert] = "You must be signed in to view private topics"
      redirect_to new_session_path
    end
  end

  def new
    @topics = Topic.visible_to(current_user)
    @topic = Topic.new
  end

  def create
    @topics = Topic.visible_to(current_user)
    @topic = Topic.new(topic_params)

    if @topic.save
      @topic.labels = Label.update_labels(params[:topic][:labels])
      flash[:notice] = "The topic was successfully saved."
      redirect_to @topic
    else
      flash.now[:alert] = "Error creating topic. Please try again later."
      render :new
    end
  end

  def edit
    @topics = Topic.visible_to(current_user)
    @topic = Topic.find(params[:id])
  end

  def update
     @topic = Topic.find(params[:id])
     @topic.assign_attributes(topic_params)

     if @topic.save
       @topic.labels = Label.update_labels(params[:topic][:labels])
       flash[:notice] = "Topic was updated successfully."
       redirect_to @topic
     else
       flash.now[:alert] = "Error saving topic. Please try again."
       render :edit
     end
   end

   def destroy
     @topic = Topic.find(params[:id])

     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the topic."
       render :show
     end
   end

   private

   def topic_params
     params.require(:topic).permit(:name, :description, :public)
   end

   def authorize_user
     unless current_user.admin?
       flash[:alert] = "You must be an admin to do that"
       redirect_to topics_path
     end
   end

end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end
end

app/views/topics/_navbar.html.erb
<div id="nav" class="navbar-fixed-top" style="background-color:white">
  <ul>
    <div id="nav-left">
      <div id="left-title">
        <% if current_user %>
          <li class="logo-font"><%= link_to 'SayIt', topics_path, style: 'color:#FF9800;text-transform: uppercase;font-size:2.4em;margin-right:30px;' %></li>
        <% else %>
          <li class="logo-font"><%= link_to 'SayIt', root_path, style: 'color:#FF9800;text-transform: uppercase;font-size:2.4em;margin-right:30px;' %></li>
        <% end %>
      </div>
      <div id="left-menu">
        <li style="color:#FF9800;"><%= link_to 'Topics', topics_path %></li>
        <li style="color:#FF9800;"><%= link_to 'Categories', topics_path %></li>
      </div>
    </div>
    <div class="nav-right">
        <% if current_user %>
          <li>
            <%= image_tag current_user.avatar_url(48), class: 'gravatar' %>
          </li>
          <li>
            <%= link_to current_user.name, user_path(current_user) %>
          </li>
          <li> | </li>
          <li><%= link_to 'Sign Out', session_path(current_user), method: :delete %></li>
        <% else %>
          <li id="signin"><%= link_to 'Sign In', new_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_path %></li>
        <% end %>
    </div>
  </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/topics/edit.html.erb
<%= render partial: 'layouts/navbar' %>

<h1>Edit Topic</h1>

<div class="row">
 <div class="col-md-4">
   <p>Guidelines for topics:</p>
   <ul>
     <li>Make sure the topic is appropriate.</li>
     <li>Never insult dogs.</li>
     <li>Smile when you type.</li>
   </ul>
 </div>
 <div class="col-md-8">
   <%= form_for @topic do |f| %>
     <div class="form-group">
       <%= f.label :name %>
       <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
     </div>
     <div class="form-group">
       <%= f.label :description %>
       <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
     </div>
     <div class="form-group">
       <%= render partial: 'labels/form', locals: { f: f, labels: @topic.labels } %>
     </div>
     <div class="form-group">
       <%= f.label :public, class: 'checkbox' do %>
         <%= f.check_box :public %> Public topic
       <% end %>
     </div>
     <%= f.submit "Save", class: 'btn btn-success' %>
   <% end %>
 </div>
</div>

app/views/topics/index.html.erb
<%= render partial: 'layouts/navbar' %>

<body id="index-topics-container">
  
</body>

app/views/topics/new.html.erb
<%= render partial: 'layouts/navbar' %>

<div id="index-topics-container" class="new-topic-inputs">
  <h1>New Topic</h1>

  <div class="row">
    <div class="col-md-8">
      <%= form_for @topic do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
        </div>
        <div class="form-group">
          <%= render partial: 'labels/form', locals: { f: f, labels: @topic.labels } %>
        </div>
        <div class="form-group">
          <%= f.label :public, class: 'checkbox' do %>
            <%= f.check_box :public %> Public topic
          <% end %>
        </div>
        <%= f.submit "Save", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<%= render partial: 'layouts/navbar' %>

<div id="show-topics-container">
  <div id="topic-title">
    <p class="lead"><%= @topic.description %></p>
    <% if current_user %>
      <div class="col-md-4">
        <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn-new' %>
      </div>
    <% end %>
  </div>

  <% if user_is_authorized_for_topics? %>
    <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
    <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
  <% end %>

  <div class="row">
     <div id="show-posts-topic-container">
       <% @topic.posts.each do |post| %>
         <div class="media" id="show-topic-media">
           <div class="media-body">
             <div id="user-writer-topics">
               <div id="user-writer1">
                 <div id="user">
                   <% avatar = post.user.avatar %>
                   <% if avatar %>
                     <div class="media-left">
                       <%= image_tag avatar, class: 'media-object' %>
                     </div>
                   <% end %>
                 </div>
                 <div id="submitted">
                   <p><%= post.user.name %></p>
                   <p><%= time_ago_in_words(post.created_at) %> ago</p>
                 </div>
               </div>
               <div id="user-writer2">
                 <div id="topic-cat">
                   <p><%= link_to @topic.name, topic_post_path(@topic, post) %></p>
                 </div>
               </div>
             </div>
             <h4 class="media-heading" id="media-heading-show-posts">
               <p><%= link_to post.title, topic_post_path(@topic, post) %></p>
             </h4>
             <div id="post-body">
               <p><%= truncate(post.body, length: 300, omission: '...') { link_to 'Read More', topic_post_path(post.topic, post) } %></p>
             </div>
             <div id="likenshare-user">
               <%= render partial: 'votes/voter', locals: { post: post } %>
               <div id="comments-icon-container">
                 <div id="icon">
                   <%= image_tag('bubble.png') %>
                 </div>
                 <div class='js-comments-count' id="js-comments-count">
                   <span style="font-weight:bold;font-size:1.1em;"><%= post.comments.count %></span>
                 </div>
                 <div id="user-show-labels">
                   <%= render partial: "labels/list", locals: { labels: post.labels } %>
                 </div>
               </div>
             </div>
           </div>
         </div>
       <% end %>
     </div>
  </div>
</div>