config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :topics do
    resources :posts
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get 'contact' => 'welcome#contact'
  get 'about' => 'welcome#about'
  get 'faq' => 'welcome#faq'

  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :topics, only: [:index, :show]
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings
  has_many :favorites, dependent: :destroy

  default_scope { order('rank DESC')}
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_sign_in, except: :show
  before_action :authorize_user, except: [:show, :new, :create]

  def show
    @post = Post.find(params[:id])
    @topics = Topic.visible_to(current_user)
  end

  def new
    @topics = Topic.visible_to(current_user)
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    @post.user = current_user

    if @post.save
      @post.labels = Label.update_labels(params[:post][:labels])
      redirect_to [@topic, @post]
    else
      render :new
    end
  end

  def edit
    @topics = Topic.visible_to(current_user)
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)

    if @post.save
      @post.labels = Label.update_labels(params[:post][:labels])
      flash[:notice] = "Your post was updated successfully."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error updating your post. Please try again later."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting your post. Please try again later."
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user
    post = Post.find(params[:id])
    unless current_user == post.user || current_user.admin?
      flash[:alert] = "You must be an admin to do that"
      redirect_to [post.topic, post]
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div id="form-style">
    <%= form_group_tag(post.errors[:title]) do %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Title..." %>
    <% end %>
    <%= form_group_tag(post.errors[:body]) do %>
      <%= f.text_area :body, class: 'form-control', placeholder: "Share your ideas..." %>
    <% end %>
    <div class="form-group">
      <%= render partial: 'labels/form', locals: { f: f, labels: @post.labels } %>
    </div>
    <div class="form-group" id="submit-new-post">
      <%= f.submit "Publish", class: 'btn btn-new-post' %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media" id="show-profile-container">
 <div class="media-body" id="user-show-post">
   <div class="media-heading" id="show-post-body">

     <div id="user-writer">
       <div id="user">
         <% avatar = @user.avatar %>
         <% if avatar %>
           <div class="media-left">
             <%= image_tag avatar, class: 'media-object' %>
           </div>
         <% end %>
       </div>
       <div id="submitted">
         <p><%= @user.name %></p>
         <p><%= time_ago_in_words(post.created_at) %> ago</p>
       </div>
     </div>

     <div id="post-body">
       <%= link_to post.title, topic_post_path(post.topic, post) %>
       <p><%= truncate(post.body, length: 230, omission: '...') { link_to 'Read More', topic_post_path(post.topic, post) } %></p>
     </div>

     <div id="likenshare-user">
       <%= render partial: 'votes/voter', locals: { post: post } %>
       <div id="comments-icon-container">
         <div id="icon">
           <%= image_tag('bubble.png') %>
         </div>
         <div class='js-comments-count' id="js-comments-count">
           <span style="font-weight:bold;font-size:1.1em;"><%= post.comments.count %></span>
         </div>
         <div id="user-show-labels">
           <%= render partial: "labels/list", locals: { labels: post.labels } %>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/posts/edit.html.erb
<%= render partial: 'layouts/navbar' %>

<div id="new-post-container">
  <div id="new-post-title">
    <div id="title">
      <h1>EDIT POST — <span style="font-style:italic">Draft</span></h1>
    </div>
    <div id="publish-save">
      <button>Save for later</button>
    </div>
  </div>
  <div class="row" id="new-post-md-container">
    <div class="col-md-8">
      <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
    </div>

    <div id="md-cheatsheet">
      <div id="md-desc">
        <p>We handle Markdown!</p>
      </div>
      <div id="md-sheet">
        <div id="cheat">
          <div style="font-weight:bold">**bold**</div>
          <div style="font-style:italic">_italic_</div>
          <div>**bold**</div>
        </div>
        <div id="cheat">
          <div>`code`</div>
          <div>> quote</div>
          <div>- bullet list</div>
        </div>
        <div id="cheat">
          <div># title</div>
          <div>## subtitle</div>
          <div>### sub-subtitle</div>
        </div>
        <div id="cheat">
          <div>Enter x3: line breaks</div>
        </div>
        <div id="cheat">
          <div style="background-color:#FF9800"><%= link_to 'Click here for more', 'https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet', target: '_blank' %></div>
        </div>
      </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render partial: 'layouts/navbar' %>

<div id="new-post-container">
  <div id="new-post-title">
    <div id="title">
      <h1>NEW POST — <span style="font-style:italic">Draft</span></h1>
    </div>
    <div id="publish-save">
      <button>Save for later</button>
    </div>
  </div>
  <div class="row" id="new-post-md-container">
    <div class="col-md-8">
      <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
    </div>
    <div id="md-cheatsheet">
      <div id="md-desc">
        <p>We handle Markdown!</p>
      </div>
      <div id="md-sheet">
        <div id="cheat">
          <div style="font-weight:bold">**bold**</div>
          <div style="font-style:italic">_italic_</div>
          <div>**bold**</div>
        </div>
        <div id="cheat">
          <div>`code`</div>
          <div>> quote</div>
          <div>- bullet list</div>
        </div>
        <div id="cheat">
          <div># title</div>
          <div>## subtitle</div>
          <div>### sub-subtitle</div>
        </div>
        <div id="cheat">
          <div>Enter x3: line breaks</div>
        </div>
        <div id="cheat">
          <div style="background-color:#FF9800"><%= link_to 'Click here for more', 'https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet', target: '_blank' %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render partial: 'layouts/navbar' %>

<div id="show-post-container">
  <div id="show-post-title-container">

    <div id="post-user-show">
      <div>
        <% avatar = @post.user.avatar %>
        <% if avatar %>
          <div class="media-left">
            <%= image_tag avatar, class: 'media-object' %>
          </div>
        <% end %>
      </div>
      <div id="post-user-order">
        <p><%= @post.user.name %></p>
        <p><%= time_ago_in_words(@post.created_at) %> ago</p>
      </div>
    </div>

     <h1>
       <%= @post.title %> <br>
     </h1>

  </div>

  <div class="row">
    <div class="col-md-8">
      <%= render partial: "labels/list", locals: { labels: @post.labels } %>
    </div>
  </div>
  <br />

  <div class="row">
    <div class="col-md-8">
      <div id="post-body-container">
        <p><%= markdown(@post.body) %></p>
      </div>
      <div id="separate"></div>
      <div id="likenshare" class="likenshare-position">
        <%= render partial: 'votes/voter', locals: { post: @post } %>
        <div id="comments-icon-container">
          <div id="icon">
            <%= image_tag('bubble.png') %>
          </div>
          <div class='js-comments-count' id="js-comments-count">
            <span style="font-weight:bold;font-size:1.1em;"><%= @post.comments.count %></span>
          </div>
        </div>
      </div>
      <div class="new-comment">
        <% if current_user %>
           <%= render 'comments/form', comment: Comment.new, post: @post %>
        <% end %>
      </div>
      <div class="js-comments">
         <%= render @post.comments %>
      </div>

    </div>
    <% if user_is_authorized_for_post?(@post) %>
      <div class="col-md-4">
        <%= link_to "Edit Post", edit_topic_post_path(@post.topic, @post), class: 'btn-edit' %>
        <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn-delete', data: {confirm: 'Are you sure you want to delete this post?'} %>
      </div>
    <% end %>
  </div>
</div>