config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :topics do
    resources :posts
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get 'contact' => 'welcome#contact'
  get 'about' => 'welcome#about'
  get 'faq' => 'welcome#faq'

  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :topics, only: [:index, :show]
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true

  after_create :send_favorite_emails

  default_scope { order('updated_at ASC') }

  private

  def send_favorite_emails
    post.favorites.each do |favorite|
      FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
    end
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/label.rb
class Label < ActiveRecord::Base

  has_many :labelings
  has_many :topics, through: :labelings, source: :labelable, source_type: :Topic
  has_many :posts, through: :labelings, source: :labelable, source_type: :Post

  def self.update_labels(label_string)
    return Label.none if label_string.blank?
    label_string.split(",").map do |label|
      Label.find_or_create_by!(name: label.strip)
    end
  end

end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
  belongs_to :labelable, polymorphic: true
  belongs_to :label
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings
  has_many :favorites, dependent: :destroy

  default_scope { order('rank DESC')}
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  default_scope { order('updated_at DESC') }


  # Scope is a method that generates methods
  # Its first argument is the name of the method to generate
  # Its second argument provides the logic to run:
        # We use the lambda syntax (-> with a block { ... }) to implement
        # the method's logic
  # the visible_to scope will run the code inside the lambda on the relation
  # or class on which it's called
  # To make it work properly we require an if statement in TopicsController to
  # determine if a user is signed in.
  # lambda block's syntax:
      # This syntax is called the ternary operator:
      # if_this_is_a_true_value ? then_the_result_is_this : else_it_is_this
      # It's like an if statement like:
          # if A then B else C end is the same as a ? b : c
  scope :visible_to, -> (user) { user ? all : where(public: true) }
  # It now returns the equivalent of Topic.all or Topic.where(public: true)
  # depending on the value of user (present or nil)


end

app/models/user.rb
class User < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_create :generate_auth_token

  before_save { self.email = email.downcase if email.present? }
  before_save { self.role ||= :member }

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  validates :password, presence: true, length: { minimum: 6 }, unless: :password_digest
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :avatar, presence: true
  validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 254 }

   has_secure_password

   enum role: [:member, :admin]

   def favorite_for(post)
     favorites.where(post_id: post.id).first
   end

   def avatar_url(size)
     gravatar_id = Digest::MD5::hexdigest(self.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
   end

   def generate_auth_token
     loop do
       self.auth_token = SecureRandom.base64(64)
       break unless User.find_by(auth_token: auth_token)
     end
   end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private

  def update_post
    post.update_rank
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

  def markdown(text)options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions = {
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true,
      autolink: true,
      tables: true,
      underline: true,
      highlight: true,
      prettify: true
      })
    markdown.render(text).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
  def labels_to_buttons(labels)
    raw labels.map { |l| link_to l.name, label_path(id: l.id), class: 'btn-sm label-container' }.join(' ')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def create_session(user)
    session[:user_id] = user.id
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
  
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar-fixed-top navbar-others" style="background-color:white">
  <ul>
    <div id="nav-left" class="nav-left-others">
      <div id="left-title">
        <% if current_user %>
          <li class="sayit-logo"><%= link_to image_tag('sayit.png'), topics_path %></li>
          <li class="logo-font"><%= link_to 'SayIt', topics_path, style: 'color:#00BCD4;text-transform: uppercase;font-size:2.4em;margin-right:30px;' %></li>
        <% else %>
          <li class="sayit-logo"><%= link_to image_tag('sayit.png'), root_path %></li>
          <li class="logo-font"><%= link_to 'SayIt', root_path, style: 'color:#00BCD4;text-transform: uppercase;font-size:2.4em;margin-right:30px;' %></li>
        <% end %>
      </div>
    </div>
    <div class="nav-right nav-right-others">
        <% if current_user %>
          <% if user_is_authorized_for_topics? %>
            <li id="add-topic">
              <%= link_to 'New Topic', new_topic_path, style: 'color:#00BCD4' %>
            </li>
          <% end %>
          <li><%= image_tag('search.png') %></li>
          <li><%= image_tag('bell.png') %></li>
          <li>
            <%= image_tag current_user.avatar, class: 'gravatar', style: 'width:40px;height:40px' %>
          </li>
          <li><%= link_to 'Sign Out', session_path(current_user), method: :delete, style: 'color:#00BCD4' %>
        <% else %>
          <li id="signin"><%= link_to 'Sign In', new_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_path %></li>
        <% end %>
    </div>
  </ul>

  <div id="cat-menu">
    <% @topics.each do |topic| %>
    <ul class="topics">
      <li><%= link_to topic.name, topic %></li>
    </ul>
    <% end %>
  </div>
</div>

app/views/layouts/_navbarindex.html.erb
<div id="nav" class="navbar-fixed-top">
  <ul>
    <div id="nav-left">
      <div id="left-title">
        <% if current_user %>
          <li class="logo-font"><%= link_to 'SayIt', topics_path, style: 'color:#FF9800;text-transform: uppercase;font-size:2.4em;margin-right:30px;' %></li>
        <% else %>
          <li class="logo-font"><%= link_to 'SayIt', root_path, style: 'color:#FF9800;text-transform: uppercase;font-size:2.4em;margin-right:30px;' %></li>
        <% end %>
      </div>
      <div id="left-menu">
        <li><%= link_to 'Categories', topics_path %></li>
      </div>
    </div>
    <div class="nav-right">
        <% if current_user %>
          <li>
            <%= image_tag current_user.avatar_url(48), class: 'gravatar' %>
          </li>
          <li>
            <%= link_to current_user.name, user_path(current_user) %>
          </li>
          <li> | </li>
          <li><%= link_to 'Sign Out', session_path(current_user), method: :delete %></li>
        <% else %>
          <li id="signin"><%= link_to 'Sign In', new_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_path %></li>
        <% end %>
    </div>
  </ul>
</div>

app/views/layouts/_navbarprofile.html.erb
<div class="navbar-fixed-top navbar-others" style="background-color:white">
  <ul>
    <div id="nav-left" class="nav-left-others">
      <div id="left-title">
        <% if current_user %>
          <li class="sayit-logo"><%= link_to image_tag('sayit.png'), topics_path %></li>
          <li class="logo-font"><%= link_to 'SayIt', topics_path, style: 'color:#00BCD4;text-transform: uppercase;font-size:2.4em;margin-right:30px;' %></li>
        <% else %>
          <li class="sayit-logo"><%= link_to image_tag('sayit.png'), root_path %></li>
          <li class="logo-font"><%= link_to 'SayIt', root_path, style: 'color:#00BCD4;text-transform: uppercase;font-size:2.4em;margin-right:30px;' %></li>
        <% end %>
      </div>
    </div>
    <div class="nav-right nav-right-others">
        <% if current_user %>
          <% if user_is_authorized_for_topics? %>
            <li id="add-topic">
              <%= link_to 'New Topic', new_topic_path, style: 'color:#00BCD4' %>
            </li>
          <% end %>
          <li><%= link_to image_tag('search.png'), session_path(current_user), method: :delete %></li>
          <li><%= link_to image_tag('bell.png'), session_path(current_user), method: :delete %></li>
          <li>
            <%= image_tag current_user.avatar, class: 'gravatar', style: 'width:40px;height:40px' %>
          </li>
          <li>
            <%= link_to current_user.name, user_path(current_user), style: 'color:#00BCD4' %>
          </li>
        <% else %>
          <li id="signin"><%= link_to 'Sign In', new_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_path %></li>
        <% end %>
    </div>
  </ul>
</div>

<div id="navbar-profile">
  <div class="row" id="profile-position">
     <div class="media" id="profile-pic">
       <br />
       <% avatar = @user.avatar %>
       <% if avatar %>
         <div class="media-left">
           <%= image_tag avatar, class: 'media-object' %>
         </div>
       <% end %>
       <div class="media-body" id="profile-info">
         <h2 class="media-heading" id="profile-info-user"><%= @user.name %></h2>
         <div id="followers">
           <p><span style="font-weight:bold">287</span> Followers</p>
           <p><span style="font-weight:bold">260</span> Following</p>
         </div>
         <div id="social">
           <%= link_to image_tag('fb.png') %>
           <%= link_to image_tag('twitter.png') %>
           <%= link_to image_tag('linkedin-logo.png') %>
         </div>
       </div>
     </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SayIt</title>
  <meta name="viewport" content="width=device-width,initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="flash">
     <% if flash[:notice] %>
       <div class="alert alert-done">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>
   </div>

<%= yield %>

<footer class="footer">
  <div id="footer-container">
    <div id="copyright">
      <p style="color:rgb(0, 150, 136);margin-left:30px;font-size:0.6em">&copy; Justine Dupuis — SayIt
    </div>
    <div id="map" class="subcat">
      <ul>
        <li>About</li>
      </ul>
    </div>
    <div id="other" class="subcat">
      <ul>
        <li>Trending topics</li>
      </ul>
    </div>
    <div class="subcat">
      <ul id="donate">
        <li><%= link_to image_tag('fb.png') %></li>
        <li><%= link_to image_tag('messenger.png') %></li>
      </ul>
    </div>
  </div>
</footer>

</div>

</body>
</html>